language: android
sudo: enabled
android:
  commonents:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-27
  - extra
before_install:
    - chmod +x gradlew
    - mkdir "$ANDROID_HOME/licenses"
    - echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
addons:
   apt:
     update: true