language: android
sudo: enabled
android:
  commonents:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-27
  - extra
before_install:
    - chmod +x gradlew
    - mkdir "$ANDROID_HOME/licenses"
    - echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
addons:
   apt:
     update: true
script:
   - ./gradlew assembleRelease
deploy:
  provider: releases
  api_key:
    secure: ea6cdea67bdf240f6cc4874fffb319afe9a1770f
  file: app/build/outputs/apk/release/ftpd.apk
  skip_cleanup: true
  on:
    tags: true